{% set name = "qasync" %}
{% set version = "0.27.1" %}
{% set sha256 = "8dc768fd1ee5de1044c7c305eccf2d39d24d87803ea71189d4024fb475f4985f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.5.0
  run:
    - python >={{ python_min }}

test:
  requires:
    - pyqt
    - python {{ python_min }}
  imports:
    - qasync

about:
  home: https://github.com/CabbageDevelopment/qasync
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Implementation of the PEP 3156 Event-Loop with Qt.

  description: |
    qasync allows coroutines to be used in PyQt/PySide applications by
    providing an implementation of the PEP 3156 event-loop.
  dev_url: https://github.com/CabbageDevelopment/qasync

extra:
  recipe-maintainers:
    - ales-erjavec
